consult:
  host: bj-cdb-6slgqwlc.sql.tencentcdb.com
  port: 62120
  user: work
  password: Gengmei1
  db: diagnosis
  charset: utf8
  cursorclass: pymysql.cursors.DictCursor

merchant:
  host: bj-cdb-6slgqwlc.sql.tencentcdb.com
  port: 62120
  user: work
  password: Gengmei1
  db: diagnosis2
  charset: utf8
  cursorclass: pymysql.cursors.DictCursor

