consult:
  host: bj-cdb-8fjm4voq.sql.tencentcdb.com
  port: 62106
  user: work
  password: Gengmei1
  db: diagnosis
  charset: utf8
  cursorclass: pymysql.cursors.DictCursor

merchant:
  host: bj-cdb-8fjm4voq.sql.tencentcdb.com
  port: 62106
  user: work
  password: Gengmei1
  db: diagnosis2
  charset: utf8
  cursorclass: pymysql.cursors.DictCursor

